package com.neocoretechs.bigsack.io.pooled;

import java.io.IOException;
import java.lang.ref.SoftReference;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

import com.neocoretechs.bigsack.DBPhysicalConstants;
import com.neocoretechs.bigsack.io.IoInterface;
import com.neocoretechs.bigsack.io.MultithreadedIOManager;
import com.neocoretechs.bigsack.io.Optr;
import com.neocoretechs.bigsack.io.RecoveryLogManager;
import com.neocoretechs.bigsack.io.ThreadPoolManager;
import com.neocoretechs.bigsack.io.stream.DBInputStream;
import com.neocoretechs.bigsack.io.stream.DBOutputStream;

/**
 * This class provides encapsulation and management of the database block page pool, the block cursor class,
 * and the recovery manager and the primary IO manager {@link MultithreadedIOManager}.<p/> 
 * We maintain an array of {@link BlockStream}, one for each tablespace. The BlockStream encapsulates a {@link MappedBlockBuffer}.
 * To each MappedBlockBuffer is added a BlockStream as a BlockChangeObserver. When a block changes as we iterate through
 * the linked list the observer is notified so that it can keep current and deliver the proper block in the stream
 * without intervention. This allows us to write contiguous blocks across block boundaries.<p/>
 * Much of the initialization occurs in 'createPool', which is called iteratively for each tablespace as supporting classes are constructed.<p/>
 * Since this class sits above the various tablespace-specific managers, it deals with virtual logical blocks vs physical ones and therefore
 * all references to blocks are virtual and the specific tablespaces and physical blocks must be extracted.<p/>
 * Since the {@link MappedBlockBuffer}s for each tablespace and the cursor class {@link BlockStream} are
 * all being serviced by different threads, and calls back and forth to the IOManagers occur,
 * this class serves as a central point for accessing those aggregate buffer pool classes.<p/>
 * The MappedBlockBuffer blockBuffer moves its retrieved blocks into the BlockStream cursor block through
 * the action of this class, as the MappedblockBuffer has no knowledge of the streams or {@link RecoveryLogManager} recovery log.<p/>
 * @see IOManagerInterface
 * @author Jonathan Groff (C) NeoCoreTechs 2021
 */
public class BufferPool {
	private static final boolean DEBUG = false;
	private GlobalDBIO globalDBIO;
	private MappedBlockBuffer[] blockBuffer; // block number to Datablock
	private RecoveryLogManager[] undoLog;
	//private BlockStream[] blockStream = new BlockStream[DBPhysicalConstants.DTABLESPACES];
	private String[] ioWorkerNames; // worker thread group names
	/**
	 * Create the {@link MappedBlockBuffer} and {@link RecoverLogManager}
	 * @param ioWorkerNames the thread names used to spin threads via the {@link ThreadPoolManager}
	 */
	public BufferPool(GlobalDBIO globalDBIO, String[] ioWorkerNames) {
		this.globalDBIO = globalDBIO; 
		this.ioWorkerNames = ioWorkerNames;
		blockBuffer = new MappedBlockBuffer[DBPhysicalConstants.DTABLESPACES];
		undoLog = new RecoveryLogManager[DBPhysicalConstants.DTABLESPACES];
	}
	
	/**
	 * Return the MappedBlockBuffer for the tablespace
	 */
	public synchronized MappedBlockBuffer getBlockBuffer(int tblsp) { 
		return blockBuffer[tblsp]; 
	}
	
	/**
	 * Set the passed MappedBlockBuffer array as the page pool for each tablespace
	 * @param blockBuffer
	 */
	public synchronized void setBlockBuffer(MappedBlockBuffer[] blockBuffer) {
		this.blockBuffer = blockBuffer;
	}

	/**
	 * Get the RecoveryLogManager for a particular tablespace
	 * @param tablespace
	 * @return
	 */
	public synchronized RecoveryLogManager getUlog(int tablespace) {
		return undoLog[tablespace];
	}


	
	/**
	 * Create the MappedBlockBuffer block pools, block pool cursor, and recovery log managers for each tablespace
	 * @param globalIO the Global IO manager
	 * @param ioManager The IOManagerInterface {@code MultithreadedIOManager}
	 * @param tablespace The target tablespace for which to create the pool elements
	 * @throws IOException
	 */
	public synchronized void createPool(IoInterface ioWorker, int tablespace) throws IOException {
		blockBuffer[tablespace] = new MappedBlockBuffer(ioWorker, tablespace);
		//blockStream[tablespace] = new BlockStream(tablespace, blockBuffer[tablespace]);
		undoLog[tablespace] = new RecoveryLogManager(globalDBIO,tablespace);
		// Set the BlockStream as an observer of the block change events generated by 'getnextblk' in MappedBlockbuffer
		//blockBuffer[tablespace].addBlockChangeObserver(blockStream[tablespace]);
	}
	
	//public synchronized void reInitLog(GlobalDBIO globalIO, int tablespace) throws IOException {
	//	undoLog[tablespace].getLogToFile().initializeLogFileSequence();
	//}
	/**
	 * Perform a rollback recovery from the recovery log files
	 * @param i
	 * @throws IOException
	 */
	public synchronized void recover(int i) throws IOException {
		undoLog[i].getLogToFile().recover();	
	}
	/**
	 * Write the headers for the blocks after allocating the blocks for a newly created database.
	 * @param ioWorker The {@link IOWorker} for the tablespace to initialize
	 * @throws IOException 
	 */
	public synchronized void initialize(IoInterface ioWorker) throws IOException {
		long endBl = ioWorker.Fsize() - (long) DBPhysicalConstants.DBLOCKSIZ;
		Datablock d = new Datablock();
		d.resetBlock();
		while (endBl >= 0L) {
			ioWorker.FseekAndWrite(endBl, d);
			endBl -= (long) DBPhysicalConstants.DBLOCKSIZ; // set up next block end
		}
		ioWorker.Fforce();	
	}
	
	/**
	* Find or add the block to in-mem list.  First deallocate the currently
	* used block, get the new block, then allocate it
	* @param tbn The virtual block
	* @return the tablespace extracted from the passed virtual block number
	* @exception IOException If low-level access fails
	*/
	private synchronized int findOrAddBlock(long tbn, DBInputStream blockStream) throws IOException {
		int tblsp = GlobalDBIO.getTablespace(tbn);
		// If the current entry is the one we are looking for, set byteindex to 0 and return
		// if not, call 'dealloc' and find our target
		if(blockStream.getBlockAccessIndex() != null ) {
			if(blockStream.getBlockAccessIndex().getBlockNum() != tbn) {
				blockStream.getBlockAccessIndex().decrementAccesses();
			} else {
				blockStream.getBlockAccessIndex().byteindex = 0;
				return tblsp;
			}
		}
		blockStream.setBlockAccessIndex(blockBuffer[tblsp].findOrAddBlock(tbn, true));
		if( DEBUG )
			System.out.println("BufferPool.findOrAddBlock RETURN tablespace "+tblsp+" pos:"+GlobalDBIO.valueOf(tbn));
		return tblsp;
	}
	
	/**
	* Find or add the block to in-mem list.  First deallocate the currently
	* used block, get the new block, then allocate it
	* @param tbn The virtual block
	* @return the tablespace extracted from the passed virtual block number
	* @exception IOException If low-level access fails
	*/
	private synchronized int findOrAddBlock(long tbn, DBOutputStream blockStream) throws IOException {
		int tblsp = GlobalDBIO.getTablespace(tbn);
		// If the current entry is the one we are looking for, set byteindex to 0 and return
		// if not, call 'dealloc' and find our target
		if(blockStream.getBlockAccessIndex() != null ) {
			if(blockStream.getBlockAccessIndex().getBlockNum() != tbn) {
				blockStream.getBlockAccessIndex().decrementAccesses();
			} else {
				blockStream.getBlockAccessIndex().byteindex = 0;
				return tblsp;
			}
		}
		blockStream.setBlockAccessIndex(blockBuffer[tblsp].findOrAddBlock(tbn, true));
		if( DEBUG )
			System.out.println("BufferPool.findOrAddBlock RETURN tablespace "+tblsp+" pos:"+GlobalDBIO.valueOf(tbn));
		return tblsp;
	}
	
	public Callable<Object> callRollback(MappedBlockBuffer blockBuffer, RecoveryLogManager logManager) { 
		return () -> {
			blockBuffer.forceBufferClear();
			//logManager.rollBack();
			return true;
		};
	}
	
	public synchronized void rollback() {
		if( DEBUG )
			System.out.printf("%s.rollback()%n",this.getClass().getName());
		
		Future<?>[] futureArray = new Future<?>[DBPhysicalConstants.DTABLESPACES];
		// queue to each tablespace
		try {
			globalDBIO.getIOManager().Fforce(); // make sure we synch our main file buffers
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i] = ThreadPoolManager.getInstance().spin(callRollback(blockBuffer[i], undoLog[i]), ioWorkerNames[i]);
			}
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i].get();
				undoLog[i].rollBack();
			}
		} catch (ExecutionException | InterruptedException | IOException e) {
			throw new RuntimeException(e);
		}
		
	}
	
	public Callable<Object> callForceBufferClear(MappedBlockBuffer blockBuffer) { 
		return () -> {
			blockBuffer.forceBufferClear();
			return true;
		};
	}
	/**
	 * Force a clearing of the page pool.
	 */
	public synchronized void forceBufferClear() {
		//for(int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
		//		blockBuffer[i].forceBufferClear();
		//}
		if( DEBUG )
			System.out.printf("%s.forceBufferClear()%n",this.getClass().getName());
		Future<?>[] futureArray = new Future<?>[DBPhysicalConstants.DTABLESPACES];
		// queue to each tablespace
		try {
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i] = ThreadPoolManager.getInstance().spin(callForceBufferClear(blockBuffer[i]), ioWorkerNames[i]);
			}
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i].get();
			}
		} catch (ExecutionException | InterruptedException e) {	}
	}
	
	public void deallocOutstanding(BlockAccessIndex bai) throws IOException { 
		bai.decrementAccesses();
	}
	

	/**
	 * Write the block to the log then unlatch it by decrementing accesses.
	 * @param tablespace The tablespace
	 * @param lbai2 The block, which is presumably outside the pool
	 * @throws IOException
	 */
	public synchronized void deallocOutstandingWriteLog(int tablespace, BlockAccessIndex lbai2) throws IOException {
		if( lbai2.getAccesses() == 1 && lbai2.getBlk().isIncore() && !lbai2.getBlk().isInlog()) {
			// will set incore, inlog, and push to raw store via applyChange of Loggable
			undoLog[tablespace].writeLog(lbai2);
			lbai2.decrementAccesses();
		} else {
			throw new IOException("BufferPool.deallocOutstandingWriteLog failed to dealloc intended target tablespace:"+tablespace);
		}
	}
	
	public synchronized BlockAccessIndex addBlockAccess(BlockAccessIndex blk) throws IOException {
		int tblsp = GlobalDBIO.getTablespace(blk.getBlockNum());
		return blockBuffer[tblsp].addBlockAccess(blk);
	}
	/**
	 * Formulate a request to the page buffer to bring target page into the pool and latch it.
	 * @param bn The target virtual block number
	 * @return
	 * @throws IOException 
	 */
	public synchronized BlockAccessIndex findOrAddBlockAccess(long bn) throws IOException {
		if( DEBUG )
			System.out.printf("%s.findOrAddBlockAccess %s%n",this.getClass().getName(),GlobalDBIO.valueOf(bn));
		int tblsp = GlobalDBIO.getTablespace(bn);
		return blockBuffer[tblsp].findOrAddBlock(bn, true);
	}
	
	public Callable<Object> callCommitBufferFlush(MappedBlockBuffer blockBuffer, RecoveryLogManager logManager) { 
		return () -> {
			blockBuffer.commitBufferFlush(logManager);
			return true;
		};
	}
	
	public Callable<Object> callCommit(MappedBlockBuffer blockBuffer, RecoveryLogManager logManager) { 
		return () -> {
			logManager.commit(blockBuffer);
			return true;
		};
	}
	/**
	 * Commit the current buffers and flush the page pools of buffered pages.
	 * @param ioWorker The array of IOWorkers to handle each commit request.
	 * @throws IOException 
	 */
	public synchronized void commitBufferFlush() throws IOException {
		// queue to each tablespace
		//for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
		//		blockBuffer[i].commitBufferFlush(ulog[i]);
		//		ulog[i].commit(blockBuffer[i]);
		//}
			if( DEBUG )
				System.out.printf("%s.commitBufferFlush()%n",this.getClass().getName());
			Future<?>[] futureArray = new Future<?>[DBPhysicalConstants.DTABLESPACES];
			// queue to each tablespace
			try {
				for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
					futureArray[i] = ThreadPoolManager.getInstance().spin(callCommitBufferFlush(blockBuffer[i], undoLog[i]), ioWorkerNames[i]);
				}
				for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
					futureArray[i].get();
					if(DEBUG)
						System.out.printf("%s next commitBufferFlush for tablespace %d%n", this.getClass().getName(),i);
				}
			} catch (InterruptedException | ExecutionException e) {
				throw new IOException(e);
			}
			// now initiate the commit for each tablespace
			//try {
				//for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				//	futureArray[i] = ThreadPoolManager.getInstance().spin(callCommit(blockBuffer[i], undoLog[i]), ioWorkerNames[i]);
				//}
				for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
					//futureArray[i].get();
					undoLog[i].commit(blockBuffer[i]);
					if(DEBUG)
						System.out.printf("%s next commit for tablespace %d%n", this.getClass().getName(),i);
				}
			//} catch (InterruptedException | ExecutionException e) {
			//	throw new IOException(e);
			//}
	}
	
	//public Callable<Object> callCheckpoint(RecoveryLogManager logManager) { 
	//	return () -> {
	//		logManager.checkpoint();
	//		return true;
	//	};
	//}
	/**
	 * Checkpoint the current buffers and flush the page pools of buffered pages.
	 * @param ioWorker The array of IOWorkers to handle each checkpoint request.
	 * @throws IOException 
	 * @throws IllegalAccessException 
	 */
	public synchronized void checkpointBufferFlush() throws IOException, IllegalAccessException {
		//globalDBIO.forceBufferWrite();
		//for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
		//	blockBuffer[i].commitBufferFlush(ulog[i]);
		//	ulog[i].checkpoint();
		//}
		if( DEBUG )
			System.out.printf("%s.checkpointBufferFlush()%n",this.getClass().getName());
		Future<?>[] futureArray = new Future<?>[DBPhysicalConstants.DTABLESPACES];
		// queue to each tablespace
		try {
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i] = ThreadPoolManager.getInstance().spin(callCommitBufferFlush(blockBuffer[i], undoLog[i]), ioWorkerNames[i]);
			}
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i].get();
				if(DEBUG)
					System.out.printf("%s next checkpointBufferFlush for tablespace %d%n", this.getClass().getName(),i);
			}
		} catch (InterruptedException | ExecutionException e) {
			throw new IOException(e);
		}
		// now initiate the commit for each tablespace
		//try {
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				//futureArray[i] = ThreadPoolManager.getInstance().spin(callCheckpoint(undoLog[i]), ioWorkerNames[i]);
				undoLog[i].checkpoint();
			}
			//for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				//futureArray[i].get();
				//if(DEBUG)
					//System.out.printf("%s next checkpoint for tablespace %d%n", this.getClass().getName(),i);
			//}
		//} catch (InterruptedException | ExecutionException e) {
		//	throw new IOException(e);
		//}
	}
	/*
	public Callable<Object> callDirectBufferWrite(MappedBlockBuffer blockBuffer) { 
		return () -> {
			blockBuffer.directBufferWrite();
			return true;
		};
	}
	*/
	/**
	 * Create a request to send to each block buffer of each tablespace to write the outstanding blocks
	 * in each of their buffers. Use a countdownlatch to await each tablespace completion.
	 * @throws IOException 
	 
	public synchronized void directBufferWrite() throws IOException {
		//for(int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
		//		blockBuffer[i].directBufferWrite();
		//}
		if( DEBUG )
			System.out.printf("%s.directBufferWrite()%n",this.getClass().getName());
		Future<?>[] futureArray = new Future<?>[DBPhysicalConstants.DTABLESPACES];
		// queue to each tablespace
		try {
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i] = ThreadPoolManager.getInstance().spin(callDirectBufferWrite(blockBuffer[i]), ioWorkerNames[i]);
			}
			for (int i = 0; i < DBPhysicalConstants.DTABLESPACES; i++) {
				futureArray[i].get();
				if(DEBUG)
					System.out.printf("%s next directBufferWrite for tablespace %d%n", this.getClass().getName(),i);
			}
		} catch (InterruptedException | ExecutionException e) {
			throw new IOException(e);
		}
	}
	*/
	/**
	 * Seek the block buffer cursor forward by a specific offset.
	 * @param tblsp The tablespace to seek
	 * @param offset The offset to seek it by
	 * @return true if the seek was successful
	 * @throws IOException
	 */
	public synchronized boolean seekFwd(DBInputStream blockStream, int tblsp, long offset) throws IOException {
		return blockStream.seek_fwd(blockStream.getBlockAccessIndex(), offset);
	}
	
	/**
	 * Write osize bytes current block buffer cursor position.
	 * @param tblsp The tablespace to write to
	 * @param o The byte array to write
	 * @param osize The number of bytes to write
	 * @throws IOException
	 */
	public synchronized void writen(DBOutputStream blockStream, int tblsp, byte[] o, int osize) throws IOException {
		blockStream.writen(blockStream.getBlockAccessIndex(), o, osize);
	}
	
	/**
	 * Delete Osize bytes from the address block and offset
	 * @param adr The virtual block and offset within that block to delete
	 * @param osize The number of bytes to delete
	 * @return The tablespace for fluent interfacing
	 * @throws IOException
	 */
	public synchronized int deleten(DBOutputStream blockStream, Optr adr, int osize) throws IOException {
		int tblsp = objseek(blockStream, adr);
		blockStream.deleten(blockStream.getBlockAccessIndex(), osize);
		return tblsp;
	}
	
	/**
	* objseek - seek to offset within block
	* @param adr block/offset to seek to
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBInputStream blockStream, Optr adr) throws IOException {
		assert(adr.getBlock() != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr.getBlock(), blockStream);
		blockStream.getBlockAccessIndex().setByteindex(adr.getOffset());
		return tblsp;
	}
	/**
	* objseek - seek to offset within block
	* @param adr block/offset to seek to
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBOutputStream blockStream, Optr adr) throws IOException {
		assert(adr.getBlock() != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr.getBlock(), blockStream);
		blockStream.getBlockAccessIndex().setByteindex(adr.getOffset());
		return tblsp;
	}
	/**
	* objseek - seek to offset within block
	* @param adr long block to seek to, block is a virtual block
	* @return the tablespace extracted from passed pointer
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBInputStream blockStream, long adr) throws IOException {
		assert(adr != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr, blockStream);
		blockStream.getBlockAccessIndex().setByteindex((short) 0);
		return tblsp;
	}

	/**
	* objseek - seek to offset within block
	* @param adr long block to seek to, block is virtual
	* @return the tablespace extracted from passed pointer
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBInputStream blockStream, long adr, short offset) throws IOException {
		assert(adr != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr, blockStream);
		blockStream.getBlockAccessIndex().setByteindex(offset);
		return tblsp;
	}
	/**
	* objseek - seek to offset within block
	* @param adr long block to seek to, block is a virtual block
	* @return the tablespace extracted from passed pointer
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBOutputStream blockStream, long adr) throws IOException {
		assert(adr != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr, blockStream);
		blockStream.getBlockAccessIndex().setByteindex((short) 0);
		return tblsp;
	}

	/**
	* objseek - seek to offset within block
	* @param adr long block to seek to, block is virtual
	* @return the tablespace extracted from passed pointer
	* @exception IOException If problem seeking block
	* @see Optr
	*/
	public synchronized int objseek(DBOutputStream blockStream, long adr, short offset) throws IOException {
		assert(adr != -1L) : "objseek Sentinel block seek error";
		int tblsp = findOrAddBlock(adr, blockStream);
		blockStream.getBlockAccessIndex().setByteindex(offset);
		return tblsp;
	}
	
}
